package conf

const (
	GRAMMER_BIND_VERTEX_COMMAND = "@BV"
	GRAMMER_CREATE_VERTEX_COMMAND = "@CV"
	GRAMMER_SET_VERTEX_TYPE_COMMAND = "@SVT"
	GRAMMER_SET_VERTEX_PROPERTY_COMMAND = "@SpV"
	GRAMMER_REMOVE_VERTEX_COMMAND = "@RV"
	GRAMMER_FILTER_VERTEX_BY_TYPE_COMMAND = "@FVBT"
	GRAMMER_IN_EDGE_COMMAND = "@InE"
	GRAMMER_OUT_EDGE_COMMAND = "@OutE"
	GRAMMER_SHOW_VERTEX_COMMAND = "@ShowV"

	GRAMMER_BIND_EDGE_COMMAND = "@BE"
	GRAMMER_CREATE_EDGE_COMMAND = "@CE"
	GRAMMER_SET_EDGE_TYPE_COMMAND = "@SET"
	GRAMMER_SET_EDGE_PROPERTY_COMMAND = "@SpE"
	GRAMMER_REMOVE_EDGE_COMMAND = "@RE"
	GRAMMER_FILTER_EDGE_BY_TYPE_COMMAND = "@FEBT"
	GRAMMER_EDGE_START_COMMAND = "@Start"
	GRAMMER_EDGE_END_COMMAND = "@End"
	GRAMMER_SHOW_EDGE_COMMAND = "@ShowE"
)

const (
	GRAMMER_BIND_VERTEX = 1001
	GRAMMER_CREATE_VERTEX = 10002
	GRAMMER_SET_VERTEX_TYPE = 10003
	GRAMMER_SET_VERTEX_PROPERTY = 10004
	GRAMMER_REMOVE_VERTEX = 10005
	GRAMMER_FILTER_VERTEX_BY_TYPE = 1002
	GRAMMER_IN_EDGE = 1003
	GRAMMER_OUT_EDGE = 1004
	GRAMMER_SHOW_VERTEX = 1005

	GRAMMER_BIND_EDGE = 2001
	GRAMMER_CREATE_EDGE = 20002
	GRAMMER_SET_EDGE_TYPE = 20003
	GRAMMER_SET_EDGE_PROPERTY = 20004
	GRAMMER_REMOVE_EDGE = 20005
	GRAMMER_FILTER_EDGE_BY_TYPE = 2002
	GRAMMER_EDGE_START = 2003
	GRAMMER_EDGE_END = 2004
	GRAMMER_SHOW_EDGE = 2005
)