package conf

var (
	VerbMap = map[string]int32{}
)

func init() {
	VerbMap[GRAMMER_BIND_VERTEX_COMMAND] = GRAMMER_BIND_VERTEX
	VerbMap[GRAMMER_CREATE_VERTEX_COMMAND] = GRAMMER_CREATE_VERTEX
	VerbMap[GRAMMER_SET_VERTEX_TYPE_COMMAND] = GRAMMER_SET_VERTEX_TYPE
	VerbMap[GRAMMER_SET_VERTEX_PROPERTY_COMMAND] = GRAMMER_SET_VERTEX_PROPERTY
	VerbMap[GRAMMER_REMOVE_VERTEX_COMMAND] = GRAMMER_REMOVE_VERTEX
	VerbMap[GRAMMER_FILTER_VERTEX_BY_TYPE_COMMAND] = GRAMMER_FILTER_VERTEX_BY_TYPE
	VerbMap[GRAMMER_IN_EDGE_COMMAND] = GRAMMER_IN_EDGE
	VerbMap[GRAMMER_OUT_EDGE_COMMAND] = GRAMMER_OUT_EDGE
	VerbMap[GRAMMER_SHOW_VERTEX_COMMAND] = GRAMMER_SHOW_VERTEX

	VerbMap[GRAMMER_BIND_EDGE_COMMAND] = GRAMMER_BIND_EDGE
	VerbMap[GRAMMER_CREATE_EDGE_COMMAND] = GRAMMER_CREATE_EDGE
	VerbMap[GRAMMER_SET_EDGE_TYPE_COMMAND] = GRAMMER_SET_EDGE_TYPE
	VerbMap[GRAMMER_SET_EDGE_PROPERTY_COMMAND] = GRAMMER_SET_EDGE_PROPERTY
	VerbMap[GRAMMER_REMOVE_EDGE_COMMAND] = GRAMMER_REMOVE_EDGE
	VerbMap[GRAMMER_FILTER_EDGE_BY_TYPE_COMMAND] = GRAMMER_FILTER_EDGE_BY_TYPE
	VerbMap[GRAMMER_EDGE_START_COMMAND] = GRAMMER_EDGE_START
	VerbMap[GRAMMER_EDGE_END_COMMAND] = GRAMMER_EDGE_END
	VerbMap[GRAMMER_SHOW_EDGE_COMMAND] = GRAMMER_SHOW_EDGE
}

const (
	GRAMMER_BIND_VERTEX_COMMAND = "@BV"
	GRAMMER_CREATE_VERTEX_COMMAND = "@CV"
	GRAMMER_SET_VERTEX_TYPE_COMMAND = "@SVT"
	GRAMMER_SET_VERTEX_PROPERTY_COMMAND = "@SVP"
	GRAMMER_REMOVE_VERTEX_COMMAND = "@RV"
	GRAMMER_FILTER_VERTEX_BY_TYPE_COMMAND = "@FVBt"
	GRAMMER_IN_EDGE_COMMAND = "@InE"
	GRAMMER_OUT_EDGE_COMMAND = "@OutE"
	GRAMMER_SHOW_VERTEX_COMMAND = "@ShowV"

	GRAMMER_BIND_EDGE_COMMAND = "@BE"
	GRAMMER_CREATE_EDGE_COMMAND = "@CE"
	GRAMMER_SET_EDGE_TYPE_COMMAND = "@SET"
	GRAMMER_SET_EDGE_PROPERTY_COMMAND = "@SEP"
	GRAMMER_REMOVE_EDGE_COMMAND = "@RE"
	GRAMMER_FILTER_EDGE_BY_TYPE_COMMAND = "@FEBt"
	GRAMMER_EDGE_START_COMMAND = "@Start"
	GRAMMER_EDGE_END_COMMAND = "@End"
	GRAMMER_SHOW_EDGE_COMMAND = "@ShowE"
)

const (
	GRAMMER_BIND_VERTEX = 1001
	GRAMMER_CREATE_VERTEX = 10002
	GRAMMER_SET_VERTEX_TYPE = 10003
	GRAMMER_SET_VERTEX_PROPERTY = 10004
	GRAMMER_REMOVE_VERTEX = 10005
	GRAMMER_FILTER_VERTEX_BY_TYPE = 1002
	GRAMMER_IN_EDGE = 1003
	GRAMMER_OUT_EDGE = 1004
	GRAMMER_SHOW_VERTEX = 1005

	GRAMMER_BIND_EDGE = 2001
	GRAMMER_CREATE_EDGE = 20002
	GRAMMER_SET_EDGE_TYPE = 20003
	GRAMMER_SET_EDGE_PROPERTY = 20004
	GRAMMER_REMOVE_EDGE = 20005
	GRAMMER_FILTER_EDGE_BY_TYPE = 2002
	GRAMMER_EDGE_START = 2003
	GRAMMER_EDGE_END = 2004
	GRAMMER_SHOW_EDGE = 2005
)
