package conf

const (
	GRAMMER_BIND_VERTEX_COMMAND = "@BV"
	GRAMMER_CREATE_VERTEX_COMMAND = "@CV"
	GRAMMER_SET_VERTEX_TYPE_COMMAND = "@SVT"
	GRAMMER_SET_VERTEX_PROPERTY_COMMAND = "@SpV"
	GRAMMER_REMOVE_VERTEX_COMMAND = "@RV"
	GRAMMER_SHOW_VERTEX_COMMAND = "@ShowV"

	GRAMMER_BIND_EDGE_COMMAND = "@BE"
	GRAMMER_CREATE_EDGE_COMMAND = "@CE"
	GRAMMER_SET_EDGE_TYPE_COMMAND = "@SET"
	GRAMMER_SET_EDGE_PROPERTY_COMMAND = "@SpE"
	GRAMMER_REMOVE_EDGE_COMMAND = "@RE"
	GRAMMER_SHOW_EDGE_COMMAND = "@ShowE"
)

const (
	GRAMMER_BIND_VERTEX = 1001
	GRAMMER_CREATE_VERTEX = 10002
	GRAMMER_SET_VERTEX_TYPE = 10003
	GRAMMER_SET_VERTEX_PROPERTY = 10004
	GRAMMER_REMOVE_VERTEX = 10005
	GRAMMER_SHOW_VERTEX = 1002

	GRAMMER_BIND_EDGE = 2001
	GRAMMER_CREATE_EDGE = 20002
	GRAMMER_SET_EDGE_TYPE = 20003
	GRAMMER_SET_EDGE_PROPERTY = 20004
	GRAMMER_REMOVE_EDGE = 20005
	GRAMMER_SHOW_EDGE = 2002
)